version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:12-alpine
    networks:
      - traefik_net
      - postgres_net
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgresusr
      - POSTGRES_PASSWORD=postgrespwd
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data:rw
      - ./dumps:/dumps

networks:
  postgres_net:
    external: true
  traefik_net:
    external: true
